---

- name: APT update
  apt: update_cache=yes cache_valid_time=3600

- name: APT upgrade
  apt: upgrade=dist state=latest

- name: Installing packages
  apt: name='aptitude,mc,ntp,git,screen,vim,bash-completion,xorg,chromium-browser,authselect,net-tools' state=latest

- name: Remove shitz
  apt: name='liblxc1,lxc,dnsmasq,lxcfs,lxc-templates' state=absent purge=yes
