---
- name: Create override.conf for auto-login
  copy:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --autologin {{ autologin_user }} --noclear %I $TERM
  notify: reload_systemd

- name: Ensure .bash_profile exists
  copy:
    dest: /home/{{ autologin_user }}/.bash_profile
    content: |
      if [[ -z $DISPLAY ]] && [[ $(tty) == /dev/tty1 ]]; then
          startx
    owner: "{{ autologin_user }}"
    group: "{{ autologin_user }}"
    mode: "0644"

- name: Ensure .xinitrc exists
  copy:
    dest: /home/{{ autologin_user }}/.xinitrc
    content: |
      exec chromium-browser --kiosk --start-fullscreen --noerrdialogs --disable-infobars
    owner: "{{ autologin_user }}"
    group: "{{ autologin_user }}"
    mode: "0755"
