---
- name: Ensure destination directory exists
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
    
- name: Create override.conf for auto-login
  copy:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --autologin senso --noclear %I $TERM
  notify: reload_systemd

- name: Ensure .bash_profile exists
  copy:
    dest: /home/senso/.bash_profile
    content: |
      if [[ -z $DISPLAY ]] && [[ $(tty) == /dev/tty1 ]]; then
          startx
    owner: "senso"
    group: "senso"
    mode: "0644"

- name: Ensure .xinitrc exists
  copy:
    dest: /home/senso/.xinitrc
    content: |
      exec chromium-browser --kiosk --start-fullscreen --noerrdialogs --disable-infobars
    owner: "senso"
    group: "senso"
    mode: "0755"
