---
    - name: Ensure destination directory exists
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create override.conf for auto-login
      copy:
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin {{ autologin_user }} --noclear %I $TERM
      notify: reload_systemd

    - name: Ensure .bash_profile exists
      copy:
        dest: /home/{{ autologin_user }}/.bash_profile
        content: |
          if [[ -z "$DISPLAY" ]] && [[ $(tty) == /dev/tty1 ]]; then
              startx
          fi
        owner: "{{ autologin_user }}"
        group: "{{ autologin_group }}"
        mode: "0644"

    - name: Ensure xorg conf exists
      copy:
        dest: /etc/X11/xorg.conf.d/99-v3d.conf
        content: |
          Section "OutputClass"
              Identifier "vc4"
              MatchDriver "vc4"
              Driver "modesetting"
              Option "PrimaryGPU" "true"
          EndSection
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Ensure .xinitrc exists
      copy:
        dest: /home/{{ autologin_user }}/.xinitrc
        content: |
          exec chromium-browser --kiosk --start-fullscreen --noerrdialogs --disable-infobars
        owner: "{{ autologin_user }}"
        group: "{{ autologin_group }}"
        mode: "0755"

    - name: Set desired and fallback DNS servers
      blockinfile:
        path: /etc/systemd/resolved.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          [Resolve]
          DNS=10.6.12.101
          FallbackDNS=8.8.8.8 1.1.1.1

    # 2. Ellenőrizd a symbolic linket a resolv.conf-hoz
    - name: Ensure resolv.conf is managed by systemd-resolved
      file:
        path: /etc/resolv.conf
        state: link
        src: /run/systemd/resolve/stub-resolv.conf

