---
# Fő feladatok
- name: Ensure destination directory exists
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create override.conf for auto-login
  copy:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --autologin senso --noclear %I $TERM
  notify: reload_systemd

- name: Ensure .bash_profile exists
  copy:
    dest: /home/senso/.bash_profile
    content: |
      if [[ -z "$DISPLAY" ]] && [[ $(tty) == /dev/tty1 ]]; then
          startx
      fi
    owner: "senso"
    group: "senso"
    mode: "0644"

- name: Ensure xorg conf exists
  copy:
    dest: /etc/X11/xorg.conf.d/99-v3d.conf
    content: |
      Section "OutputClass"
          Identifier "vc4"
          MatchDriver "vc4"
          Driver "modesetting"
          Option "PrimaryGPU" "true"
      EndSection
    owner: "root"
    group: "root"
    mode: "0644"

- name: Ensure .xinitrc exists
  copy:
    dest: /home/senso/.xinitrc
    content: |
      exec chromium-browser --kiosk --start-fullscreen --noerrdialogs --disable-infobars
    owner: "senso"
    group: "senso"
    mode: "0755"

# Handlers blokk
handlers:
  - name: reload_systemd
    command: systemctl daemon-reload
