---
- name: Configure Raspberry Pi for auto-login and Chromium kiosk mode
  hosts: ugyfelhivo1
  become: yes
  vars:
    autologin_user: "senso"  # Replace with your target username

  tasks:
    - name: Ensure Chromium and Xorg are installed
      apt:
        name:
          - chromium-browser
          - xorg
          - xserver-xorg
        state: present
        update_cache: yes

    - name: Create override.conf for auto-login
      copy:
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin {{ autologin_user }} --noclear %I $TERM
      notify: reload_systemd

    - name: Ensure .bash_profile exists
      copy:
        dest: /home/{{ autologin_user }}/.bash_profile
        content: |
          if [[ -z $DISPLAY ]] && [[ $(tty) == /dev/tty1 ]]; then
              startx
          fi
      owner: "{{ autologin_user }}"
      group: "{{ autologin_user }}"
      mode: "0644"

    - name: Ensure .xinitrc exists
      copy:
        dest: /home/{{ autologin_user }}/.xinitrc
        content: |
          exec chromium-browser --kiosk --start-fullscreen --noerrdialogs --disable-infobars
      owner: "{{ autologin_user }}"
      group: "{{ autologin_user }}"
      mode: "0755"

  handlers:
    - name: reload_systemd
      command: systemctl daemon-reload
