---
    - name: Ensure necessary packages are installed
      apt:
        name:
          - sssd
          - sssd-tools
          - realmd
          - adcli
          - samba-common
          - krb5-user
          - packagekit
        state: present
        update_cache: yes

    - name: Configure Kerberos default realm in debconf
      debconf:
        name: krb5-config
        question: krb5-config/default_realm
        value: "{{ ad_realm }}"
        vtype: string

    - name: Discover the AD domain
      command: realm discover {{ ad_domain }}
      register: realm_discovery
      changed_when: false

    - name: Join the host to the AD domain
      command: echo "{{ ad_admin_password }}" | realm join --user={{ ad_admin_user }} {{ ad_domain }}
      args:
        executable: /bin/bash
      register: join_result
      failed_when: join_result.rc != 0

    - name: Configure SSSD to use AD for authentication
      lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^domains ='
        line: "domains = {{ ad_domain }}"
        state: present
      notify: restart_sssd

    - name: Ensure SSSD configuration file has proper permissions
      file:
        path: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: "0600"

    - name: Enable and start SSSD service
      systemd:
        name: sssd
        enabled: true
        state: started

    - name: Configure PAM to create home directories automatically
      command: "authselect select sssd with-mkhomedir --force"

    - name: Restart SSSD service
      systemd:
        name: sssd
        state: restarted
