---
    - name: Ensure necessary packages are installed
      apt:
        name:
          - sssd
          - sssd-tools
          - realmd
          - adcli
          - samba-common
          - krb5-user
          - packagekit
        state: present
        update_cache: yes

    - name: Ensure /etc/authselect directory exists
      file:
        path: /etc/authselect
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Configure Kerberos default realm in debconf
      debconf:
        name: krb5-config
        question: krb5-config/default_realm
        value: "{{ ad_realm }}"
        vtype: string

    - name: Discover the AD domain
      command: realm discover {{ ad_domain }}
      register: realm_discovery
      changed_when: false

    - name: Join the host to the AD domain
      shell: echo "{{ ad_admin_password }}" | realm join --user={{ ad_admin_user }} {{ ad_domain }}
      register: join_result
      failed_when: join_result.rc != 0

    - name: Configure SSSD to use AD for authentication
      lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^domains ='
        line: "domains = {{ ad_domain }}"
        state: present

    - name: Disable fully qualified domain names in SSSD
      lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^use_fully_qualified_names'
        line: "use_fully_qualified_names = False"
        state: present

    - name: Set default domain suffix for SSSD
      lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^default_domain_suffix'
        line: "default_domain_suffix = {{ ad_domain }}"
        state: present
      notify: restart_sssd

    - name: Ensure pam_mkhomedir is enabled in common-session
      lineinfile:
        path: /etc/pam.d/common-session
        state: present
        line: "session required pam_mkhomedir.so skel=/etc/skel umask=0077"

    - name: Ensure pam_mkhomedir is enabled in common-session-noninteractive
      lineinfile:
        path: /etc/pam.d/common-session-noninteractive
        state: present
        line: "session required pam_mkhomedir.so skel=/etc/skel umask=0077"

    # 2. SSSD konfiguráció beállítása
    - name: Configure SSSD to set home directory path
      blockinfile:
        path: /etc/sssd/sssd.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          [domain/your_domain]
          override_homedir = /home/%u

    - name: Validate SSSD configuration
      shell: sssctl config-check
      register: sssctl_check
      failed_when: "'SUCCESS' not in sssctl_check.stdout"

    - name: Ensure SSSD configuration file has proper permissions
      file:
        path: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: "0600"

    - name: Enable and start SSSD service
      systemd:
        name: sssd
        enabled: true
        state: started

    - name: Configure PAM to create home directories automatically
      shell: "authselect select sssd with-mkhomedir --force"

    - name: Restart SSSD service
      systemd:
        name: sssd
        state: restarted
    - name: Configure SSSD to restrict access to a specific AD group
      blockinfile:
        path: /etc/sssd/sssd.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR ACCESS RESTRICTIONS"
        block: |
          access_provider = simple
          simple_allow_groups = {{ allowed_ad_group }}
      notify: restart_sssd

    - name: Ensure SSH is configured to use SSSD for access control
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?AuthorizedKeysCommandUser'
        line: "AuthorizedKeysCommandUser nobody"
        state: present

    - name: Enable SSH authorization via SSSD
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?UsePAM'
        line: "UsePAM yes"
        state: present

    - name: Limit SSH access to specific AD group
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AllowGroups'
        line: "AllowGroups {{ allowed_ad_group }}"
        state: present
      notify: restart_ssh

    # 2. Hozzáadjuk a csoportot a sudoers fájlhoz
    - name: Add allowed_ad_group to sudoers
      copy:
        dest: /etc/sudoers.d/allowed_ad_group
        content: |
          %{{ allowed_ad_group }} ALL=(ALL:ALL) ALL
        owner: root
        group: root
        mode: "0440"

    - name: Restart SSH service to apply changes
      systemd:
        name: ssh
        state: restarted
