---

- name: groups > Groups configuration
  group:
    name:   "{{ item.name }}"
    system: "{{ item.system|default(false)|bool }}"
    state:  "{{ item.state|default('present') }}"
    gid:    "{{ item.gid|default(omit) }}"
  with_items: '{{users_groups|default([])}}'

