---
    - name: Ensure destination directory exists
      file:
        path: /etc/systemd/system/getty@tty1.service.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create override.conf for auto-login
      copy:
        dest: /etc/systemd/system/getty@tty1.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin {{ autologin_user }} --noclear %I $TERM
      notify: reload_systemd

- name: Ensure .xinitrc exists
  copy:
    dest: /home/{{ autologin_user }}/.xinitrc
    content: |
      connectedOutputs=xrandr | awk '{print $1" "$2}' | grep " connected" | awk '{print $1}'

      for i in $(echo $connectedOutputs | tr " " "\n")
      do
          cmd="xrandr --output $i --mode 1920x1080"
          echo $cmd
          $cmd
          cmd="xrandr --output $i --rotate right"
          echo $cmd
          $cmd
      done

      jack_control start

      /home/senso/calibrateMagic.sh
      /usr/share/touchfoildriver-LMA9/ViPstartdrv.sh &
      setxkbmap hu

      /home/senso/screenRun.sh /senso/bin/NeoInfopultWebservice/NeoInfopultWebService &
      /home/senso/screenRun.sh /senso/bin/AdvertLogger.py &

      /senso/bin/NeoInfopult/NeoInfopult
    owner: "{{ autologin_user }}"
    group: "{{ autologin_group }}"
    mode: "0644"

- name: infopult.ini set
  copy:
    dest: /senso/bin/NeoInfopult/config/infopult.ini
    content: |
      videoOnly=true
      videoPlayerWidth=1080
      videoPlayerHeight=1920

    - name: infopult client.ini set
      copy:
        dest: /senso/bin/NeoInfopultWebservice/client.ini
        content: |
		"{{ client.ini }}"
    - name: Ensure xorg conf exists
      copy:
        dest: /etc/X11/xorg.conf.d/99-v3d.conf
        content: |
          Section "OutputClass"
              Identifier "vc4"
              MatchDriver "vc4"
              Driver "modesetting"
              Option "PrimaryGPU" "true"
          EndSection
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Ensure .bash_profile exists
      copy:
        dest: /home/{{ autologin_user }}/.bash_profile
        content: |
	          if shopt -q login_shell; then
             [[ -f ~/.bashrc ]] && source ~/.bashrc
             [[ -z "$DISPLAY" ]] && [[ $(tty) == /dev/tty1 ]] && exec startx -- -nocursor
          else
             exit 1 
          fi

        owner: "{{ autologin_user }}"
        group: "{{ autologin_group }}"
        mode: "0755"

    - name: Set desired and fallback DNS servers
      blockinfile:
        path: /etc/systemd/resolved.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          [Resolve]
          DNS=10.6.12.101
          FallbackDNS=8.8.8.8 1.1.1.1

    # 2. Ellenőrizd a symbolic linket a resolv.conf-hoz
    - name: Ensure resolv.conf is managed by systemd-resolved
      file:
        path: /etc/resolv.conf
        state: link
        src: /run/systemd/resolve/stub-resolv.conf

    - name: Restart systemd-resolved service
      service:
        name: systemd-resolved
        state: restarted

    # 1. Remove all MOTD scripts
    - name: Remove MOTD update scripts
      file:
        path: /etc/update-motd.d/
        state: absent

    # 2. Disable MOTD in PAM configuration
    - name: Comment out pam_motd.so in common-session
      lineinfile:
        path: /etc/pam.d/common-session
        regexp: '^session\s+optional\s+pam_motd.so.*'
        state: absent
        backrefs: yes

    - name: Comment out pam_motd.so in common-session-noninteractive
      lineinfile:
        path: /etc/pam.d/common-session-noninteractive
        regexp: '^session\s+optional\s+pam_motd.so.*'
        state: absent
        backrefs: yes

    # 3. Disable dynamic MOTD updates
    - name: Disable dynamic MOTD updates in SSHD
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PrintMotd\s+yes'
        line: 'PrintMotd no'
        state: present

    - name: Ensure PrintLastLog is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PrintLastLog\s+yes'
        line: 'PrintLastLog no'
        state: present

    - name: Create a cron job to ping VPN server every minute
      cron:
        name: "Ping VPN server to keep connection alive"
        minute: "*/2"
        job: "/bin/ping -c 3 10.6.1.1 > /dev/null 2>&1"

